consul:
  image: progrium/consul
  hostname: node1
  ports:
  - "192.168.1.15:8300:8300"
  - "192.168.1.15:8301:8301"
  - "192.168.1.15:8301:8301/udp"
  - "192.168.1.15:8302:8302"
  - "192.168.1.15:8302:8302/udp"
  - "192.168.1.15:8400:8400"
  - "8001:8500"
  - "172.17.42.1:53:53/udp"
  volumes:
    - ~/docker-consul/config:/etc/configs:ro
  command: -server -advertise 192.168.1.15 -bootstrap-expect 3

registrator:
  command: consul://192.168.1.15:8001
  privileged: true
  image: progrium/registrator
  links:
  - consul
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock

nginx:
  build: ./
  environment:
    SERVICE_NAME: nginx
    SERVICE_TAGS: loadbalancer
  ports:
  - "8000:80"
  links:
  - consul
